# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-25 06:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='titulo',
            field=models.CharField(max_length=75),
        ),
    ]
