# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-27 01:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0002_auto_20170125_0010'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='linkEvento',
            field=models.CharField(default='', max_length=75),
        ),
    ]
