# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-11 20:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0003_evento_linkevento'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='imagen',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='media/Eventos/'),
            preserve_default=False,
        ),
    ]
