# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-11 20:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0004_evento_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='linkUbicacion',
            field=models.CharField(default='', max_length=200),
        ),
    ]
