# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-01 21:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriber', '0002_auto_20170801_2137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriber',
            name='ciudad',
            field=models.CharField(max_length=30, null=True, verbose_name='Ciudad'),
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='email',
            field=models.CharField(max_length=30, verbose_name='Correo Eléctronico'),
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='nombre',
            field=models.CharField(max_length=30, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='pais',
            field=models.CharField(max_length=30, null=True, verbose_name='País'),
        ),
    ]
