# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-01 21:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriber', '0003_auto_20170801_2146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriber',
            name='email',
            field=models.EmailField(max_length=30, unique=True, verbose_name='Correo Eléctronico'),
        ),
    ]
