# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-29 22:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Integrante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30, verbose_name='Nombre')),
                ('instrumento', models.CharField(max_length=30, verbose_name='Instrumento')),
                ('biografia', models.TextField()),
                ('fecha_salida', models.DateField()),
            ],
        ),
    ]
