# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-29 22:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bio_info', '0002_integrante_imagen'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='media/biografia/')),
                ('biografia', models.TextField()),
                ('fecha_salida', models.DateField()),
            ],
        ),
    ]
