# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-10 21:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bio_info', '0003_banda'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Integrante',
            new_name='Miembro',
        ),
    ]
