# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-11 22:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bio_info', '0004_auto_20171210_2116'),
    ]

    operations = [
        migrations.AddField(
            model_name='miembro',
            name='id_pagina',
            field=models.CharField(default=django.utils.timezone.now, max_length=30, verbose_name='Id_pagina'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='miembro',
            name='imagen_home',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='media/home/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='miembro',
            name='imagen_prensa',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='media/prensa/'),
            preserve_default=False,
        ),
    ]
