# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-29 22:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Disco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('anno', models.PositiveSmallIntegerField()),
                ('nombre_banda', models.CharField(default='Lalalá', max_length=15)),
                ('integrantes', models.CharField(default='Kevin Calvo, Kenneth Calvo, Roberto Cruz', max_length=10)),
                ('info', models.TextField()),
                ('ficha_tecnica', models.TextField()),
                ('imagen', models.CharField(max_length=30)),
            ],
        ),
    ]
