# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-15 09:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musica', '0004_auto_20161229_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disco',
            name='imagen',
            field=models.ImageField(upload_to=''),
        ),
    ]
