# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-15 10:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musica', '0005_auto_20170115_0351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disco',
            name='imagen',
            field=models.ImageField(upload_to='site_media'),
        ),
    ]
