# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-11 06:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('musica', '0008_disco_nombdisco'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ficha_Tecnica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('letra', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='disco',
            name='ficha_tecnica',
        ),
        migrations.AddField(
            model_name='ficha_tecnica',
            name='disco',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='musica.Disco'),
        ),
    ]
