# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-11 17:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('musica', '0010_auto_20170811_0623'),
    ]

    operations = [
        migrations.AddField(
            model_name='disco',
            name='imagen_grande',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='media/Discos/'),
            preserve_default=False,
        ),
    ]
