# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-26 02:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musica', '0012_auto_20170826_0242'),
    ]

    operations = [
        migrations.RenameField(
            model_name='disponible_en_sencillo',
            old_name='nombre',
            new_name='plataforma',
        ),
    ]
