# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-26 02:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musica', '0013_auto_20170826_0252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disponible_en_sencillo',
            name='plataforma',
            field=models.CharField(choices=[('Spotify', 'Spotify'), ('Deezer', 'Deezer'), ('Apple Music', 'Apple Music')], default='Spotify', max_length=12),
        ),
    ]
