# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-01 21:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musica', '0014_auto_20170826_0255'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sencillo',
            name='compartir_facebook',
        ),
        migrations.RemoveField(
            model_name='sencillo',
            name='compartir_twiter',
        ),
    ]
