# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-02 03:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musica', '0015_auto_20170901_2119'),
    ]

    operations = [
        migrations.AddField(
            model_name='sencillo',
            name='nombre_banda',
            field=models.CharField(default='Lalalá', max_length=15),
        ),
    ]
