# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-10 22:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('musica', '0017_disco_fecha_salida'),
    ]

    operations = [
        migrations.CreateModel(
            name='Disponible_En_Disco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plataforma', models.CharField(choices=[('Spotify', 'Spotify'), ('Deezer', 'Deezer'), ('Apple Music', 'Apple Music'), ('Amazon Music', 'Amazon Music')], default='Spotify', max_length=15)),
                ('link', models.URLField()),
            ],
        ),
        migrations.RemoveField(
            model_name='disponible_en_sencillo',
            name='sencillo',
        ),
        migrations.RemoveField(
            model_name='ficha_tecnica_sencillo',
            name='sencillo',
        ),
        migrations.AddField(
            model_name='disco',
            name='playlist_spotify',
            field=models.CharField(default=django.utils.timezone.now, max_length=45),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Disponible_En_Sencillo',
        ),
        migrations.DeleteModel(
            name='Ficha_Tecnica_Sencillo',
        ),
        migrations.DeleteModel(
            name='Sencillo',
        ),
        migrations.AddField(
            model_name='disponible_en_disco',
            name='disco',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='musica.Disco'),
        ),
    ]
