# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-17 06:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musica', '0018_auto_20170910_2211'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('url', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='disponible_en_disco',
            name='plataforma',
            field=models.CharField(choices=[('Spotify', 'Spotify'), ('Deezer', 'Deezer'), ('Apple Music', 'Apple Music'), ('Amazon Music', 'Amazon Music'), ('YouTube', 'YouTube')], default='Spotify', max_length=15),
        ),
    ]
