# Generated by Django 2.0.1 on 2018-01-12 23:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('musica', '0020_auto_20170917_0605'),
    ]

    operations = [
        migrations.CreateModel(
            name='Link_SmartLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plataforma', models.CharField(choices=[('Spotify', 'Spotify'), ('Deezer', 'Deezer'), ('Apple Music', 'Apple Music'), ('Amazon Music', 'Amazon Music'), ('iTunes', 'iTunes'), ('Google Play Music', 'Google Play Music'), ('BandCamp', 'BandCamp'), ('Napster', 'Napster')], default='Spotify', max_length=15)),
                ('link', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='SmartLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=75)),
                ('nombSmart', models.CharField(max_length=75)),
                ('imagen', models.ImageField(upload_to='media/smartLink/')),
                ('colorFondo', models.CharField(max_length=6)),
            ],
        ),
        migrations.AddField(
            model_name='link_smartlink',
            name='smartlink',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='musica.SmartLink'),
        ),
    ]
