# Generated by Django 2.0.1 on 2018-01-12 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musica', '0021_auto_20180112_2305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link_smartlink',
            name='link',
            field=models.CharField(max_length=200),
        ),
    ]
