# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-30 04:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Enlace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=75)),
                ('url', models.CharField(max_length=200)),
                ('fecha_salida', models.DateField()),
            ],
            options={
                'ordering': ['-fecha_salida'],
            },
        ),
        migrations.CreateModel(
            name='Foto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('descripcion', models.CharField(blank=True, max_length=200, null=True, verbose_name='Descripción')),
                ('imagen', models.ImageField(upload_to='media/imagen_prensa/')),
                ('fecha_salida', models.DateField()),
                ('updated', models.DateField(auto_now=True)),
            ],
            options={
                'ordering': ['-fecha_salida'],
            },
        ),
        migrations.CreateModel(
            name='Integrante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30, verbose_name='Nombre')),
                ('instrumento', models.CharField(max_length=30, verbose_name='Instrumento')),
                ('imagen', models.ImageField(upload_to='media/integrante/')),
                ('fecha_salida', models.DateField()),
            ],
            options={
                'ordering': ['-fecha_salida'],
            },
        ),
        migrations.CreateModel(
            name='Press_Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('biografia', models.TextField()),
                ('propuesta_musical', models.TextField()),
                ('fecha_salida', models.DateField(auto_now=True)),
            ],
            options={
                'ordering': ['-fecha_salida'],
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=75)),
                ('url', models.CharField(max_length=50)),
                ('fecha_salida', models.DateField()),
            ],
            options={
                'ordering': ['-fecha_salida'],
            },
        ),
    ]
