# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-22 02:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('press_info', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='integrante',
            name='biografia',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='integrante',
            name='id_pagina',
            field=models.CharField(default=django.utils.timezone.now, max_length=30, verbose_name='Nombre'),
            preserve_default=False,
        ),
    ]
