# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-10 21:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('press_info', '0002_auto_20171122_0252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='integrante',
            name='id_pagina',
            field=models.CharField(max_length=30, verbose_name='Id_pagina'),
        ),
    ]
