# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-11 22:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('press_info', '0003_auto_20171210_2116'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Integrante',
        ),
    ]
