# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-06 01:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('press_info', '0004_delete_integrante'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='imagen',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='media/video_prensa/'),
            preserve_default=False,
        ),
    ]
