# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-06 01:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('press_info', '0005_video_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='descripcion',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='video',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
    ]
