# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-11 18:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Imagen_Pagina',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(choices=[('Discografía', 'Discografía'), ('Calendario', 'Calendario'), ('Prensa', 'Prensa'), ('Contacto', 'Contacto'), ('Gracias', 'Gracias')], default='Discografía', max_length=2)),
                ('imagen', models.ImageField(upload_to='media/imagen_paginas/')),
                ('fecha', models.DateField()),
            ],
        ),
    ]
