# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-11 22:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0004_auto_20170811_2000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagen_pagina',
            name='nombre',
            field=models.CharField(choices=[('DIS', 'Discografía'), ('CAL', 'Calendario'), ('BIO', 'Biografía'), ('PRE', 'Prensa'), ('CON', 'Contacto'), ('GRA', 'Gracias'), ('SUB', 'Subcribirse')], default='DIS', max_length=3),
        ),
    ]
