# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-01 21:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redireccion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='redireccionamiento',
            name='visitas',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
